[package]
name = "smart-switch"
version = "0.2.0"
edition = "2021"

[dependencies]
fastedge = { workspace = true }
serde = "1.0"
serde_json = "1.0"
url = "2.5"

[lib]
path = "smart-switch.rs"
crate-type = ["cdylib"]

